version: "3"
services:
  playground:
    # platform: linux/x86_64
    container_name: "docker-pystan"
    build: ./
    user: root
    working_dir: /notebook
    tty: true
    volumes:
      - type: bind # ホストのディレクトリをゲストにマウントさせる
        source: ../notebook # ホストの`notebook`ディレクトリを指定
        target: /notebook # ゲストの`/notebook`にマウントさせる
    ports:
      - "18889:8888"
