FROM mcr.microsoft.com/devcontainers/python:3.10-bullseye
# 標準出力と標準エラー出力をバッファリングせずに出力
ENV PYTHONUNBUFFERED 1

RUN pip install poetry

# COPY pyproject.toml* poetry.lock* ./

RUN poetry config virtualenvs.create true
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi